apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
    template:
      metadata:
      labels:
        app: app
      spec:
        containers:
        - name: app
          image: ghcr.io/tafukagawa/app-on-k8s:{{TAG}}
          ports:
            - containerPort:

