name: ci-cd

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  APP_NS: app

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Build & Test
        run: |
          ./mvnw -q -DskipTests=false test || mvn -q -DskipTests=false test || echo "skip tests"

  docker-build-push:
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        run: |
          TAG=${GITHUB_SHA::7}
          docker build -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest

  deploy:
    needs: docker-build-push
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set TAG
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - name: Apply to Kubernetes
        shell: bash
        run: |
          TAG=${{ steps.vars.outputs.TAG }}
          mkdir -p /tmp/manif
          for f in k8s/*.yml; do
            sed "s#{{TAG}}#${TAG}#g" "$f" > "/tmp/manif/$(basename "$f")"
          done
          kubectl apply -f /tmp/manif/namespace.yml
          kubectl apply -f /tmp/manif/deployment.yml
          kubectl apply -f /tmp/manif/service.yml
          kubectl -n $APP_NS rollout status deploy/app --timeout=120s